logo: /asset/wincent.jpg
rss: #/atom.xml
disqus: 
google_analytics:

# Social accounts
#instagram: wincentwang
#pinterest: wincentwang
github: wincentwang
#facebook: wincentwang
#twitter: wincentwang
#linkedin: wincentwang